# This file is best used with VS Code REST Client
# The queries can be run in any REST client, but the result may differ according to the host and the content of that server.
# Feel free to uncomment any of the following hosts to try the server.

#TEHIK FHIR terminology server (test server, not public)
@host = https://onto.k8s1.test.tehik.ee/fhir

#Ontoserver R4 public FHIR terminology server
#@host = https://r4.ontoserver.csiro.au/fhir

#Ontoserver R5 public alpha test server
#host = https://ontoserver-r5.australiaeast.cloudapp.azure.com/fhir


# GENERAL QUERIES (comment out the appropriate resource)

@resource = ValueSet
#@resource = CodeSystem
#@resource = ConceptMap
#@resource = NamingSystem

# Get all resources by type from the terminology server
###
{{host}}/{{resource}}

# Get all resources changed since date (remove prefix 'ge' for exact date)
@date = 2023-07-07

###
{{host}}/{{resource}}/?_lastUpdated=ge{{date}}

###
{{host}}/{{resource}}/?_history?_since={{date}}


# CODESYSTEM

###
{{host}}/CodeSystem

# Get CodeSystem by id
###
{{host}}/CodeSystem/pharmaceutical-dose-form-ema-cs

# CODESYSTEM CONCEPT

# Look up a specific code. Returns details of the concept from the code system.
# The default version of SNOMED CT is defined in terminology server configuration. Therefore, the response from different servers may differ.
# TEHIK terminology server uses SNOMED CT latest Estonian edition as the default version. 

###
{{host}}/CodeSystem/$lookup?system=http://snomed.info/sct&code=112144000

# You can specify the version in the request
###
{{host}}/CodeSystem/$lookup?system=http://snomed.info/sct&code=6012004&version=http://snomed.info/sct/11000181102


# Validate code against a code system or its specific version (remove version section for default version). See FHIR documentation for more parameters.
###
POST {{host}}/CodeSystem/$validate-code HTTP/1.1
content-type: application/json

{
  "resourceType" : "Parameters",
  "parameter" : [
    {
    "name" : "url",
    "valueUri" : "http://snomed.info/sct"
    }
  ,
    {
    "name" : "version",
    "valueString" : "http://snomed.info/sct/11000181102/version/20230530"
    }  
  ,
    {
      "name" : "code",
      "valueString": "261405004" 
    }
  ]
}


# VALUE SET

###
{{host}}/ValueSet


# Get value set definition by id
###
{{host}}/ValueSet/40cdb547-28fa-4e8e-8eb1-7048fe269aa9

# Get value set expansion by id 
# This provides the default expansion of the value set if it has been defined.
###
{{host}}/ValueSet/pharmaceutical-dose-form/$expand


# METADATA REQUESTS
###
{{host}}/metadata?mode=terminology



# Add/update resources

###
POST {{host}}/CodeSystem HTTP/1.1
content-type: application/json

< filename.json


###
POST {{host}}/NamingSystem HTTP/1.1
content-type: application/json

{
  "resourceType" : "NamingSystem",
  "id" : "org-vatin",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h3>Summary</h3><table class=\"grid\"><tr><td>Defining URL</td><td>https://fhir.ee/NamingSystem/org-vatin</td></tr><tr><td>Version</td><td>1.0.0</td></tr><tr><td>Name</td><td>OrgVATIN</td></tr><tr><td>Title</td><td>VAT identification number</td></tr><tr><td>Status</td><td>draft</td></tr><tr><td>Definition</td><td><div><p>VAT identification number.</p>\n</div></td></tr><tr><td>Publisher</td><td>HL7 Estonia</td></tr></table><h3>Identifiers</h3><table class=\"grid\"><tr><td><b>Type</b></td><td><b>Value</b></td><td><b>Preferred</b></td></tr><tr><td>URI</td><td>https://fhir.ee/sid/org/vatin</td><td>true</td></tr></table></div>"
  },
  "url" : "https://fhir.ee/NamingSystem/org-vatin",
  "version" : "1.0.0",
  "name" : "OrgVATIN",
  "title" : "VAT identification number",
  "status" : "draft",
  "kind" : "identifier",
  "date" : "2022-11-05T12:40:30.7439354+00:00",
  "publisher" : "HL7 Estonia",
  "contact" : [{
    "name" : "HL7 Estonia",
    "telecom" : [{
      "system" : "url",
      "value" : "https://www.hl7.ee"
    }]
  }],
  "type" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
      "code" : "TAX"
    }]
  },
  "description" : "VAT identification number.",
  "jurisdiction" : [{
    "coding" : [{
      "system" : "urn:iso:std:iso:3166",
      "code" : "EE",
      "display" : "Estonia"
    }]
  }],
  "usage" : "Used in resources defining the identifier for a taxable person (business) or non-taxable legal entity that is registered for VAT.",
  "uniqueId" : [{
    "type" : "uri",
    "value" : "https://fhir.ee/sid/org/vatin",
    "preferred" : true
  }]
}



